### ISSUE TITLE
No port exposed

### ISSUE THREAD

**Issue by silenceleaf** [ibm-datapower/datapower-labs#1]
When I run "make evolve"

it perform this command:

sudo docker run -d --name datapower --restart=on-failure --privileged -P root/datapower-factory:0.1

but no port exposed. I have to manually add parameter:

-p xxx.xxx.xxx.xxx:9090:9090

That's work for me.

**Comment by hstenzel** [comment]
Thanks for the report!

The "-P" option will map all EXPOSEd ports, and 9090 is EXPOSEd. I would expect that if you run "docker ps" with the original command that you'll see which ports were used under the "PORTS" column.

Also, if you do "make gui" or even just a make by itself, make will query Docker to find the mapped port and try to open a browser to that url.

The example uses the "-P" instead of being specific about the mapped ports to make it easier to run multiple containers at the same time. If we didn't do that, then every DataPower Docker container would try to use the same port, or you'd have a manual process to manage the mappings, and both seemed worse than letting Docker pick.

**Comment by silenceleaf** [comment]
Got you, thank you for your response!

**Comment by hstenzel** [comment]
Sounds like we're all set then. Closing.
